# Generated by Django 4.0.3 on 2022-03-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='price',
            new_name='amount',
        ),
    ]
